# Generated by Django 2.1.1 on 2018-12-07 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_auto_20181207_1804'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='upvote',
            new_name='vote',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='upvote_count',
            new_name='vote_count',
        ),
    ]
