# Generated by Django 2.1.4 on 2018-12-09 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_auto_20181207_2121'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(blank=True, choices=[('CSE', 'Computer Science and Engineering'), ('CE', 'Chemical Engineering'), ('BT', 'Bio-Technology'), ('CST', 'Chemical Science & Technology'), ('CE', 'Civil Engineering'), ('ECE', 'Electronics & Communication Engineering'), ('EEE', 'Electronics & Electrical Engineering'), ('EP', 'Engineering Physics'), ('ME', 'Mechanical Engineering'), ('MNC', 'Mathematics & Computing')], help_text='Department', max_length=3)),
                ('age', models.IntegerField()),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('degree', models.CharField(blank=True, choices=[('PhD', 'Doctorate of Philosophy'), ('B.Tech', 'Bachelor of Technology'), ('M.Tech', 'Master of Technology'), ('B.Des', 'Bachelor of Design'), ('M.Des', 'Master of Design')], help_text='Degree', max_length=6)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('profile_picture', models.ImageField(default='images/profile_pictures/default.png', upload_to='images/profile_pictures')),
                ('city', models.CharField(max_length=255)),
                ('user_id', models.IntegerField()),
            ],
        ),
    ]
