# Generated by Django 2.1.1 on 2018-12-11 15:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profiles', '0011_auto_20181210_2026'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='vote',
            new_name='upvote',
        ),
        migrations.AddField(
            model_name='post',
            name='downvote',
            field=models.ManyToManyField(related_name='downvotes', to=settings.AUTH_USER_MODEL),
        ),
    ]
