# Generated by Django 2.1.4 on 2018-12-19 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0014_auto_20181219_1343'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='title',
            field=models.CharField(default='resource', max_length=300),
            preserve_default=False,
        ),
    ]
