# Generated by Django 2.1.4 on 2018-12-20 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0015_resource_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='admin_of_courses',
            field=models.ManyToManyField(related_name='courses', to='profiles.Course'),
        ),
        migrations.AddField(
            model_name='resource',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
