# Generated by Django 2.1.4 on 2018-12-20 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0018_auto_20181220_0950'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='semester',
        ),
    ]
