# Generated by Django 2.1.4 on 2019-01-13 06:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0020_profile_admin_request'),
    ]

    operations = [
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.Course')),
                ('files', models.ManyToManyField(related_name='files', to='profiles.Resource')),
                ('folders', models.ManyToManyField(related_name='_folder_folders_+', to='profiles.Folder')),
            ],
        ),
    ]
