# Generated by Django 2.1.4 on 2019-01-13 07:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0021_folder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='folder',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='folder', to='profiles.Course'),
        ),
    ]
