# Generated by Django 2.1.4 on 2019-01-13 09:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0023_auto_20190113_0902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='folder',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='folders', to='profiles.Course'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='profiles.Course'),
        ),
    ]
