# Generated by Django 2.1.4 on 2019-01-13 11:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0024_auto_20190113_0912'),
    ]

    operations = [
        migrations.RenameField(
            model_name='folder',
            old_name='files',
            new_name='resources',
        ),
    ]
