# Generated by Django 2.1.4 on 2019-01-13 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0025_auto_20190113_1129'),
    ]

    operations = [
        migrations.AddField(
            model_name='folder',
            name='root',
            field=models.BooleanField(default=False),
        ),
    ]
