# Generated by Django 2.1.4 on 2019-01-13 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0026_folder_root'),
    ]

    operations = [
        migrations.AlterField(
            model_name='folder',
            name='folders',
            field=models.ManyToManyField(to='profiles.Folder'),
        ),
    ]
