# Generated by Django 2.1.4 on 2019-01-13 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0027_auto_20190113_1235'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resource',
            name='description',
        ),
        migrations.RemoveField(
            model_name='resource',
            name='title',
        ),
    ]
