# Generated by Django 2.1.4 on 2019-01-13 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0028_auto_20190113_1411'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resource',
            name='course',
        ),
        migrations.RemoveField(
            model_name='resource',
            name='user',
        ),
        migrations.RemoveField(
            model_name='folder',
            name='resources',
        ),
        migrations.DeleteModel(
            name='Resource',
        ),
    ]
