# Generated by Django 2.1.4 on 2019-01-13 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0030_auto_20190113_1446'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='folder',
            name='resources',
        ),
        migrations.AddField(
            model_name='resource',
            name='folder',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='resource', to='profiles.Folder'),
            preserve_default=False,
        ),
    ]
