# Generated by Django 2.1.1 on 2019-01-14 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0031_auto_20190113_1644'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='title',
            field=models.CharField(default='temp.cpp', max_length=200),
            preserve_default=False,
        ),
    ]
