# Generated by Django 2.1.4 on 2019-01-20 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0034_auto_20190115_0942'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='folder',
            name='course',
        ),
        migrations.RemoveField(
            model_name='folder',
            name='created_on',
        ),
        migrations.RemoveField(
            model_name='folder',
            name='folders',
        ),
        migrations.RemoveField(
            model_name='folder',
            name='root',
        ),
    ]
