# Generated by Django 2.1.2 on 2019-01-20 16:50

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0043_auto_20190120_1646'),
    ]

    operations = [
        migrations.AddField(
            model_name='folder',
            name='course',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='folders', to='profiles.Course'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='folder',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='folder',
            name='parent_folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subfolders', to='profiles.Folder'),
        ),
        migrations.AddField(
            model_name='folder',
            name='root',
            field=models.BooleanField(default=False),
        ),
    ]
