# Generated by Django 2.1.2 on 2019-01-20 16:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0044_auto_20190120_1650'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='tag',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
