# Generated by Django 2.1.2 on 2019-02-01 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0045_resource_tag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='admin_request',
            new_name='admin_dept',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='admin_of_courses',
        ),
    ]
